### ISSUE TITLE
error

### ISSUE THREAD

**Issue by texrg** [ColonyCounter/CascadeImgScript#1]
python samplefilecreator/samplefilecreator.py 
  File "samplefilecreator/samplefilecreator.py", line 19
    print("\tAdded: ", str_to_write, end="")
                                        ^
SyntaxError: invalid syntax

**Comment by thacoon** [comment]
Hi,
are you using Python 2?  Python2 will fail for `print("\tAdded: ", str_to_write, end="")` with an invalid syntax error. If changed to `print("\tAdded: " + "" + "\n")` it should work.
The script is written for Python 3. I have updated the README.

P.S.
I am very sorry for the late response.
